//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvvMobile.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvvMobile.Localization.TextResources", typeof(TextResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Shift.
        /// </summary>
        internal static string Add_Shift {
            get {
                return ResourceManager.GetString("Add_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Claims.
        /// </summary>
        internal static string Claim_List {
            get {
                return ResourceManager.GetString("Claim_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Profile.
        /// </summary>
        internal static string ClientProfile {
            get {
                return ResourceManager.GetString("ClientProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect Clinical Data.
        /// </summary>
        internal static string Collect_ClinicalData {
            get {
                return ResourceManager.GetString("Collect_ClinicalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Main_About {
            get {
                return ResourceManager.GetString("Main_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        internal static string Main_Chart {
            get {
                return ResourceManager.GetString("Main_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Search.
        /// </summary>
        internal static string Main_ClaimSearch {
            get {
                return ResourceManager.GetString("Main_ClaimSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string Main_Login {
            get {
                return ResourceManager.GetString("Main_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        internal static string Main_Page {
            get {
                return ResourceManager.GetString("Main_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Shifts.
        /// </summary>
        internal static string Main_Schedule {
            get {
                return ResourceManager.GetString("Main_Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Message.
        /// </summary>
        internal static string MessageDetail {
            get {
                return ResourceManager.GetString("MessageDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Messages.
        /// </summary>
        internal static string MessageList {
            get {
                return ResourceManager.GetString("MessageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Messages.
        /// </summary>
        internal static string NewMessageList {
            get {
                return ResourceManager.GetString("NewMessageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Detail.
        /// </summary>
        internal static string Schedule_Details {
            get {
                return ResourceManager.GetString("Schedule_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Calendar.
        /// </summary>
        internal static string Schedule_MyCalendar {
            get {
                return ResourceManager.GetString("Schedule_MyCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string Schedule_New {
            get {
                return ResourceManager.GetString("Schedule_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off Schedule.
        /// </summary>
        internal static string Schedule_OffSchedule {
            get {
                return ResourceManager.GetString("Schedule_OffSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Schedule.
        /// </summary>
        internal static string Schedule_Reject {
            get {
                return ResourceManager.GetString("Schedule_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        internal static string Schedule_Scheduled {
            get {
                return ResourceManager.GetString("Schedule_Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s Shifts.
        /// </summary>
        internal static string Schedule_TodayList {
            get {
                return ResourceManager.GetString("Schedule_TodayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsynced.
        /// </summary>
        internal static string Schedule_Unsync {
            get {
                return ResourceManager.GetString("Schedule_Unsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        internal static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Tracking.
        /// </summary>
        internal static string SyncLocationTracking {
            get {
                return ResourceManager.GetString("SyncLocationTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Trackings.
        /// </summary>
        internal static string SyncLocationTranking_List {
            get {
                return ResourceManager.GetString("SyncLocationTranking_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Timeline.
        /// </summary>
        internal static string TimeLine {
            get {
                return ResourceManager.GetString("TimeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Location.
        /// </summary>
        internal static string Track_Location {
            get {
                return ResourceManager.GetString("Track_Location", resourceCulture);
            }
        }
    }
}
